# Generated by Django 2.0.5 on 2019-01-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ussd', models.CharField(max_length=6)),
                ('countryTLD', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=100)),
                ('lon_lat', models.CharField(max_length=100)),
                ('ATM', models.BooleanField(default=False)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Bank')),
            ],
        ),
    ]
