# Generated by Django 2.0.5 on 2019-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='email_addresses',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bank',
            name='other_websites',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_numbers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bank',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='countryTLD',
            field=models.CharField(default='NG', max_length=2),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ussd',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='Branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='lon_lat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
